type ModelsType = {
  brand: string;
  models: string[];
};

export const carModels: ModelsType[] = [
  { brand: "All", models: [] },
  {
    brand: "BMW",
    models: [
      "All",
      "Series 1",
      "Series 2",
      "Series 3",
      "Series 4",
      "Series 5",
      "Series 6",
      "Series 7",
      "Series 8",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "M8",
      "Other",
    ],
  },
  {
    brand: "Audi",
    models: [
      "All",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q1",
      "Q2",
      "Q3",
      "Q4",
      "Q5",
      "Q6",
      "Q7",
      "S3",
      "S5",
      "S4",
      "S6",
      "S7",
      "S8",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "R8",
      "TT",
      "TT S",
      "TT RS",
      "E-tron",
      "Other",
    ],
  },
  {
    brand: "Volkswagen",
    models: [
      "All",
      "Golf",
      "Passat",
      "Tiguan",
      "Polo",
      "Touran",
      "T-Roc",
      "Caddy",
      "Arteon",
      "Taigo",
      "Other",
    ],
  },
  {
    brand: "Ford",
    models: [
      "All",
      "Focus",
      "Mondeo",
      "Kuga",
      "Fiesta",
      "S-Max",
      "C-Max",
      "Mustang",
      "Ka",
      "Other",
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      "All",
      "Class A",
      "Class B",
      "Class C",
      "Class E",
      "Class G",
      "Class R",
      "Class S",
      "Class G",
      "Class V",
      "ML",
      "CLS",
      "CLE",
      "CLA",
      "GLA",
      "GLE",
      "GLS",
      "GLC",
      "CL",
      "CLK",
      "SL",
      "SLC",
      "SLS",
      "SLK",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQS",
      "Other",
    ],
  },
  {
    brand: "Opel",
    models: [
      "All",
      "Astra",
      "Insignia",
      "Corsa",
      "Mokka",
      "Zafira",
      "Meriva",
      "Vivaro",
      "Omega",
      "Signum",
      "Vectra",
      "Other",
    ],
  },
  {
    brand: "Toyota",
    models: [
      "All",
      "Corolla",
      "Yaris",
      "RAV4",
      "Auris",
      "Avensis",
      "C-HR",
      "Aygo",
      "Supra",
      "Other",
    ],
  },
  {
    brand: "Skoda",
    models: [
      "All",
      "Octavia",
      "Superb",
      "Fabia",
      "Kodiaq",
      "Karoq",
      "Kamiq",
      "Scala",
      "Rapid",
      "Citigo",
      "Yeti",
      "Enyaq",
      "Other",
    ],
  },
  {
    brand: "Reanult",
    models: [
      "All",
      "Megane",
      "Clio",
      "Scenic",
      "Captur",
      "Laguna",
      "Trafic",
      "Kadjar",
      "Espace",
      "Alpine",
      "Espace",
      "Kangoo",
      "Talisman",
      "Twingo",
      "Modus",
      "Other",
    ],
  },
  {
    brand: "Peugeot",
    models: [
      "All",
      "106",
      "107",
      "205",
      "206",
      "207",
      "208",
      "305",
      "306",
      "307",
      "308",
      "406",
      "407",
      "408",
      "4007",
      "4008",
      "5008",
      "508",
      "607",
      "807",
      "Boxer",
      "Partner",
      "Other",
    ],
  },
  {
    brand: "Kia",
    models: [
      "All",
      "Sportage",
      "Ceed",
      "Rio",
      "Sorento",
      "XCeed",
      "Pro_ceed",
      "Stonic",
      "Stinger",
      "Other",
    ],
  },
  {
    brand: "Hyundai",
    models: [
      "All",
      "Tucson",
      "I30",
      "I40",
      "I20",
      "I10",
      "Ix35",
      "Kona",
      "Ix20",
      "Elantra",
      "Santa Fe",
      "Other",
    ],
  },
  {
    brand: "Tesla",
    models: ["All", "Model 3", "Model S", "Model X", "Roadster", "Y", "Other"],
  },
  { brand: "Bentley", models: ["All", "Bentayga", "Continental GT", "Other"] },
  {
    brand: "Chevrolet",
    models: ["All", "Camaro", "Corvette", "Cruze", "1500", "Aveo", "Other"],
  },
  {
    brand: "Citroen",
    models: [
      "All",
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C-Elysee",
      "DS3",
      "DS4",
      "DS5",
      "Xsara",
      "Other",
    ],
  },
  {
    brand: "Cupra",
    models: ["All", "Ateca", "Born", "Formentor", "Leon", "Other"],
  },
  {
    brand: "Fiat",
    models: [
      "All",
      "500",
      "500X",
      "500XL",
      "Panda",
      "Bravo",
      "Punto",
      "Grande Punto",
      "Freemont",
      "Other",
    ],
  },
  {
    brand: "Honda",
    models: ["All", "Civic", "Accord", "City", "CR-V", "HR-V", "Jazz", "Other"],
  },
  {
    brand: "Jaguar",
    models: ["All", "E-Pace", "F-Pace", "F-Type", "XE", "XF", "XJ", "Other"],
  },
  {
    brand: "Jeep",
    models: [
      "All",
      "Compass",
      "Grand Cherokee",
      "Cherooke",
      "Renegade",
      "Wrangler",
      "Compass",
      "Other",
    ],
  },
  {
    brand: "Lexus",
    models: ["All", "GS", "ES", "IS", "LC", "LS", "NX", "RX", "UX", "Other"],
  },
  {
    brand: "Mazda",
    models: [
      "All",
      "5",
      "6",
      "CX-30",
      "CX-3",
      "CX-5",
      "CX-50",
      "CX-60",
      "CX-7",
      "CX-9",
      "MX-3",
      "MX-5",
      "MX-30",
      "MX-5",
      "RX-7",
      "RX-8",
      "Other",
    ],
  },
  {
    brand: "Porsche",
    models: [
      "All",
      "718",
      "911",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "Taycan",
      "Other",
    ],
  },
  {
    brand: "Volvo",
    models: [
      "All",
      "C30",
      "C40",
      "C70",
      "S40",
      "S60",
      "S80",
      "S90",
      "V40",
      "V60",
      "V70",
      "V90",
      "XC-40",
      "XC-60",
      "XC-70",
      "XC-90",
      "Other",
    ],
  },
  {
    brand: "Suzuki",
    models: ["All", "Grand Vitara", "Jimny", "Swift", "Vitara", "Other"],
  },
  {
    brand: "Alfa Romeo",
    models: [
      "All",
      "159",
      "147",
      "Gulia",
      "Gulietta",
      "GT",
      "Stelvio",
      "Tonale",
      "Other",
    ],
  },
  {
    brand: "Dodge",
    models: [
      "All",
      "Challenger",
      "Durango",
      "RAM",
      "Viper",
      "Charger",
      "Other",
    ],
  },
  {
    brand: "Dacia",
    models: ["All", "Jogger", "Lodgy", "Duster", "Logan", "Sandero", "Other"],
  },
  {
    brand: "Mitsubishi",
    models: [
      "All",
      "ASX",
      "Carisma",
      "Colt",
      "Exlipse",
      "L200",
      "Lancer",
      "Pajero",
      "Space Star",
      "Other",
    ],
  },
  {
    brand: "Nissan",
    models: ["All", "370Z", "Almera", "GT-R", "Qashqai", "X-Trail", "Other"],
  },
];

export const fuelList: string[] = [
  "Petrol",
  "Diesel",
  "Hydrogen",
  "Electric",
  "Petrol + LPG",
  "Hybrid",
];

export const bodyTypeList: string[] = [
  "Cabriolet",
  "Wagon",
  "Compact",
  "Minivan",
  "Sedan",
  "SUV",
  "Coupe",
  "City Car",
];
export const conditionDamagedList: string[] = ["Any", "Not Damaged", "Damaged"];

export const priceList: string[] = [
  "1000",
  "2000",
  "5000",
  "10000",
  "15000",
  "20000",
  "25000",
  "30000",
  "35000",
  "40000",
  "45000",
  "50000",
  "55000",
  "60000",
  "65000",
  "70000",
  "75000",
  "80000",
  "85000",
  "90000",
  "95000",
  "100000",
  "150000",
  "200000",
  "250000",
  "500000",
  "1000000",
];
export const yearList: string[] = [
  "1900",
  "1910",
  "1920",
  "1930",
  "1940",
  "1950",
  "1960",
  "1970",
  "1980",
  "1990",
  "1991",
  "1992",
  "1993",
  "1994",
  "1995",
  "1996",
  "1997",
  "1998",
  "1999",
  "2000",
  "2001",
  "2002",
  "2003",
  "2004",
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
];

export const mileageList: string[] = [
  "20000",
  "35000",
  "50000",
  "75000",
  "100000",
  "125000",
  "150000",
  "1750000",
  "200000",
  "225000",
  "250000",
  "300000",
];
